# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TallyDiary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TallyDiary
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'Firebase/Core'

  target 'TallyDiary-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TallyDiaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
   
