export const UPDATE_ENTRIES = "UPDATE_ENTRIES";
export const UPDATE_PREFERENCES = "UPDATE_PREFERENCES";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_PREFERENCES_ID = "SET_PREFERENCES_ID";
export const SET_ENTRIES_ID = "SET_ENTRIES_ID"